Repository kida31/untitled-plant-game, pull requests merged in 2024-12, with the labels that each got.

#119 garden map for demo
  Assets/OverworldAssets/GardenDecoration/Pole_fairy_lights.png
  Assets/OverworldAssets/GardenDecoration/crates_tileset.png
  Assets/OverworldAssets/GardenDecoration/crates_tileset.png.import
  Assets/OverworldAssets/GardenDecoration/fence.png
  Assets/OverworldAssets/GardenDecoration/fence_front_variations_improved.png
  Assets/OverworldAssets/GardenDecoration/fence_front_variations_improved.png.import
  Assets/OverworldAssets/GardenDecoration/fence_side_less_shine.png
  Assets/OverworldAssets/GardenDecoration/fence_side_less_shine.png.import
  Assets/OverworldAssets/GardenDecoration/ladder_tileset_improved.png
  Assets/OverworldAssets/GardenDecoration/ladder_tileset_improved.png.import
  Assets/OverworldAssets/GardenDecoration/planters_tileset_rgb.png
  Assets/OverworldAssets/GardenDecoration/planters_tileset_rgb.png.import
  Assets/OverworldAssets/GardenDecoration/tileset_stones.png
  Assets/OverworldAssets/GardenDecoration/tileset_stones.png.import
  Assets/OverworldAssets/GardenDecoration/tileset_stones_improved.png
  Assets/OverworldAssets/GardenDecoration/tileset_stones_improved.png.import
  Assets/Sprites/charlieTheCapybaraAnimationSheet.png
  Assets/Sprites/charlieTheCapybaraAnimationSheet.png.import
  Assets/UI/arrow_down.png
  Assets/UI/arrow_down.png.import
  Assets/UI/close_x.png
  Assets/UI/close_x.png.import
  Scenes/TestScenes/GardenMapScene.tscn
Labels: enhancement, visual

#122 add garden map into main scene (game world container)
  Assets/Sprites/ExamplePlayerSprite.png
  Assets/Sprites/ExamplePlayerSprite.png.import
  Features/NPC/NPC.tscn
  Features/Player/Player.cs
  Features/Player/Player.tscn
  Scenes/GameWorldContainer.tscn
  Scenes/GardenMapScene.tscn
Labels: enhancement, visual

#124 Add HouseMap
  Assets/IndoorAssets/bed.png
  Assets/IndoorAssets/bed.png.import
  Assets/Tilesets/atlas_32x.png
  Assets/Tilesets/atlas_32x.png.import
  Scenes/GardenMapScene.tscn
  Scenes/HouseMapScene.tscn
Labels: enhancement, visual

#116 Feature/inventory and encyclopedia UI
  Assets/DefaultUPGTheme.tres
  Common/EventBus.cs
  DefaultItemBackground_Black.png
  DefaultItemBackground_Black.png.import
  DefaultItemBackground_White.png
  DefaultItemBackground_White.png.import
  Features/Inventory/GeneralInventory/GeneralInventory.tscn
  Features/Inventory/GeneralInventory/GeneralInventoryLogic.cs
  Features/Inventory/GeneralInventory/UI_InventoryItem/I_UI_InventoryItem.cs
  Features/Inventory/GeneralInventory/UI_InventoryItem/UI_InventoryItem.cs
  Features/Inventory/GeneralInventory/UI_ItemCategory/HerbCategory.cs
  Features/Inventory/GeneralInventory/UI_ItemCategory/IItemCategory.cs
  Features/Inventory/GeneralInventory/UI_ItemCategory/MedicineCategory.cs
  Features/Inventory/GeneralInventory/UI_ItemCategory/SeedCategory.cs
  Features/Inventory/GeneralInventory/UI_Tabs/HerbsTab.cs
  Features/Inventory/GeneralInventory/UI_Tabs/ICategoryTab.cs
  Features/Inventory/GeneralInventory/UI_Tabs/MedicineTab.cs
  Features/Inventory/GeneralInventory/UI_Tabs/SeedsTab.cs
  Features/Inventory/PlayerInventory/GeneralInventory.tscn
  Features/Inventory/PlayerInventory/PlayerDetailStat.tscn
  Features/Inventory/PlayerInventory/PlayerInventory.cs
  Features/Inventory/PlayerInventory/PlayerInventoryController.cs
  Features/Inventory/PlayerInventory/UI_Buttons/SwapInventoryViewUiButton.cs
  Features/Inventory/PlayerInventory/UI_Buttons/UIButton.tscn
  Features/Inventory/PlayerInventory/UI_InventoryItem/InventoryItemView.cs
  Features/Inventory/PlayerInventory/UI_InventoryItem/InventoryItemView.tscn
  Features/Inventory/PlayerInventory/UI_Screens/PlayerDetailsPage.tscn
  Features/Inventory/PlayerInventory/UI_Tabs/DetailedItemView.cs
  Features/Inventory/PlayerInventory/UI_Tabs/DetailedItemView.tscn
  Features/Inventory/PlayerInventory/UI_Tabs/HerbsTab.cs
  Features/Inventory/PlayerInventory/UI_Tabs/ICategoryTab.cs
  Features/Inventory/PlayerInventory/UI_Tabs/MedicineTab.cs
  Features/Inventory/PlayerInventory/UI_Tabs/SeedsTab.cs
  Features/Inventory/PlayerInventory/UI_Tabs/TabItemView.cs
  Features/Inventory/PlayerInventory/UI_Tabs/TabItemView.tscn
  Features/Inventory/PlayerInventory/UI_Tabs/TabsController.cs
  Features/Inventory/PlayerInventory/UI_Wiki/DetailedWikiController.cs
  Features/Inventory/PlayerInventory/UI_Wiki/DetailedWikiItemView.cs
  Features/Inventory/PlayerInventory/UI_Wiki/DetailedWikiItemView.tscn
  Features/Inventory/PlayerInventory/UI_Wiki/ScrollViewController.cs
  Features/Inventory/PlayerInventory/UI_Wiki/WikiItemView.cs
  Features/Inventory/PlayerInventory/UI_Wiki/WikiItemView.tscn
  Features/Item/InteractableItem.cs
  Features/Statistics/StatTypes/Currency.cs
  Features/Statistics/StatTypes/Faith.cs
  Features/Systems/CurrencyFaithOfficer.cs
  Hover.png
  Hover.png.import
  Resources/EntityStats_TEST_2.tres
  Scenes/TestScenes/TestInventoryScene2.tscn
  project.godot
Labels: enhancement

#156 added Tutorial Dialogue
  Assets/OverworldAssets/Plant/ChuberySpriteFrames.tres
  Assets/OverworldAssets/Plant/LicarySpriteFrames.tres
  Features/Dialogue/DialogueUI.cs
  Features/Dialogue/Dialogue_Scene.tscn
  Resources/Dialogue/HarvestingTutorialDialogue.tres
  Resources/Dialogue/SeedBoyTutorialDialogue.tres
  Resources/Dialogue/TutorialDialogue.tres
  Resources/Dialogue/TutorialDialogue2ndPart.tres
  Resources/Dialogue/TutorialDialogueEnd.tres
  Resources/Dialogue/VendingMachineTutorialDialogue.tres
  Resources/Dialogue/monologue.tres
  Scenes/GameWorldContainer.tscn
  Scenes/TestScenes/APlant/TestAPlant.tscn
  Scenes/TestScenes/Dialogue/TestDialogue.cs
  Scenes/TestScenes/Dialogue/Test_Dialogue.tscn
  Scenes/TestScenes/VendingMachineTest/VendingMachineInteractTest.tscn
Labels: content
