Repository kida31/untitled-plant-game, pull requests merged in 2025-01, with the labels that each got.

#157 Item content and descriptions
  Assets/Items/Drupoleaum_Flowers.png
  Assets/Items/Drupoleaum_Flowers.png.import
  Assets/Items/Drupoleaum_Fruits.png
  Assets/Items/Drupoleaum_Fruits.png.import
  Assets/Items/licary_flowers.png
  Assets/Items/licary_flowers.png.import
  Assets/Items/licary_harvested.png
  Assets/Items/licary_harvested.png.import
  Assets/Items/licary_leaves.png
  Assets/Items/licary_leaves.png.import
  Features/Crafting/Recipe.cs
  Features/Inventory/GUI/ItemTooltipView.cs
  Features/Inventory/IItemStack.cs
  Features/Inventory/ItemStack.cs
  Features/Inventory/PlayerInventory/UI_Wiki/DetailedWikiItemView.cs
  Features/Inventory/PlayerInventory/UI_Wiki/WikiItemView.cs
  Features/Item/ItemDatabase.cs
  Features/Item/ItemDatabaseTester.cs
  Features/Shops/RandomStockGenerator.cs
  Scenes/TestScenes/VendingMachineTest/UiOnly.cs
Labels: enhancement

#158 147 implement seed bag
  Assets/Tools/SeedBag.png
  Assets/Tools/SeedBag.png.import
  Common/EventBus.cs
  Features/GUI/HUDs/Toolbelt/ToolBlobView.cs
  Features/GUI/HUDs/Toolbelt/ToolBlobView.tscn
  Features/GUI/HUDs/Toolbelt/ToolbeltView.cs
  Features/Inventory/BigInventory.cs
  Features/Inventory/ItemCategory.cs
  Features/Inventory/ItemStack.cs
  Features/Inventory/PlayerInventory/UI_Wiki/ScrollViewController.cs
  Features/Inventory/PlayerInventory/UI_Wiki/WikiItemView.cs
  Features/Item/Components/SeedComponent.cs
  Features/Item/ItemDatabase.cs
  Features/Item/ItemDatabaseTester.cs
  Features/Plants/Plant.cs
  Features/Plants/PlantMap.cs
  Features/Plants/PlantPrefab.tscn
  Features/Plants/Soil/SoilTile.cs
  Features/Player/Player.cs
  Features/Shops/RandomStockGenerator.cs
  Features/Tools/SeedBag.cs
  Features/Tools/Shears.cs
  Features/Tools/Tool.cs
  Features/Tools/Toolbelt.cs
  Scenes/GameWorldContainer.tscn
  Scenes/SoilTiles.tscn
  Scenes/TestScenes/APlant/TestAPlant.cs
  Scenes/TestScenes/ItemDataBaseConfigTest/ItemDatabaseTester.tscn
  untitled-plant-game.csproj.DotSettings
Labels: enhancement

#117 71 implement medicine crafting mechanic
  Assets/Items/Plants/Drupoleaum_Flowers.png
  Assets/Items/Plants/Drupoleaum_Flowers.png.import
  Assets/Items/Plants/Drupoleaum_Fruits.png
  Assets/Items/Plants/Drupoleaum_Fruits.png.import
  Assets/Items/Plants/chubery_harvested.png
  Assets/Items/Plants/chubery_harvested.png.import
  Assets/Items/Plants/licary_flowers.png
  Assets/Items/Plants/licary_flowers.png.import
  Assets/Items/Plants/licary_harvested.png
  Assets/Items/Plants/licary_harvested.png.import
  Assets/Items/Plants/licary_leaves.png
  Assets/Items/Plants/licary_leaves.png.import
  Assets/UI/arrow_down.png
  Assets/UI/arrow_down.png.import
  Assets/UI/close_x.png
  Assets/UI/close_x.png.import
  Common/EventBus.cs
  Common/GameStates/GameState.cs
  Features/Crafting/CraftingSlot.cs
  Features/Crafting/CraftingSlotUi.cs
  Features/Crafting/Dehydrator/Dehydrator.cs
  Features/Crafting/Dehydrator/DehydratorUi.cs
  Features/Crafting/Dehydrator/DehydratorUi.tscn
  Features/Crafting/ICraftingStation.cs
  Features/Crafting/ICraftingStationUi.cs
  Features/Crafting/Recipe.cs
  Features/Crafting/crafting_slot.tscn
  Features/Inventory/ItemStack.cs
  Features/Item/Components/Antioxidant.cs
  Features/Item/Components/Basil.cs
  Features/Item/Components/Decoration.cs
  Features/Item/Components/DriedLeaf.cs
  Features/Item/Components/Lavender.cs
  Features/Item/Components/Leaf.cs
  Features/Item/Components/MedicineComponent.cs
  Features/Item/Components/Mint.cs
  Features/Item/Components/Nuke.cs
  Features/Item/Components/Oil.cs
  Features/Item/Components/Rose.cs
  Features/Item/Components/Spice.cs
  Features/Item/Components/Sunflower.cs
  Features/Item/Components/Sweet.cs
  Features/Item/Components/TagsComponent.cs
  Features/Item/IClonable.cs
  Features/Item/ItemDatabase.cs
  Features/Medicine/IllnessEffect.cs
  Features/Medicine/MedicinalEffect.cs
  Features/Medicine/MedicineComponent.cs
  Features/VendingMachine/UI/ItemSlot.tscn
  Features/VendingMachine/UI/ItemSlotUI.cs
  Resources/EntityStats_TEST_2.tres
  Scenes/TestScenes/Crafting/TestCrafing.cs
  Scenes/TestScenes/Crafting/Test_Crafing.tscn
Labels: enhancement

#182 [Bugfix] Fix player having to tap twice to re-open vending/seed
  Features/Interaction/InteractionManager.cs
  Features/Player/Player.cs
  Features/Player/StateIdle.cs
  Features/Player/StateWalk.cs
Labels: bug

#186 Merge in Seed Shop UI assets
  Assets/UI/SeedShop/ItemContainer_Seed_Shop.png
  Assets/UI/SeedShop/ItemContainer_Seed_Shop.png.import
  Assets/UI/SeedShop/seed_shop_cloth_flat.png
  Assets/UI/SeedShop/seed_shop_cloth_flat.png.import
Labels: visual, content

#189 183-Dialogue-lines-1-hotfix
  Resources/Dialogue/SeedBoy/ClosingLines/seed_boy_close_1.tres
  Resources/Dialogue/VendingMachine/AveragePricesResponses/average_prices_res_1.tres
  Resources/Dialogue/VendingMachine/HighPricesResponses/high_price_res_1.tres
  Resources/Dialogue/VendingMachine/LowPricesResponses/low_prices_res_1.tres
Labels: bug, content

#191 [Update/Buttons] visually update buttons and add trigger buttons
  Assets/UI/Buttons/Playstation/L2_default.png
  Assets/UI/Buttons/Playstation/L2_default.png.import
  Assets/UI/Buttons/Playstation/L2_pressed.png
  Assets/UI/Buttons/Playstation/L2_pressed.png.import
  Assets/UI/Buttons/Playstation/R2_default.png
  Assets/UI/Buttons/Playstation/R2_default.png.import
  Assets/UI/Buttons/Playstation/R2_pressed.png
  Assets/UI/Buttons/Playstation/R2_pressed.png.import
  Assets/UI/Buttons/XBOX/LT_default.png
  Assets/UI/Buttons/XBOX/LT_default.png.import
  Assets/UI/Buttons/XBOX/LT_pressed.png
  Assets/UI/Buttons/XBOX/LT_pressed.png.import
  Assets/UI/Buttons/XBOX/RT_default.png
  Assets/UI/Buttons/XBOX/RT_default.png.import
  Assets/UI/Buttons/XBOX/RT_pressed.png
  Assets/UI/Buttons/XBOX/RT_pressed.png.import
  Assets/UI/Buttons/play_button_on_hover.png
  Assets/UI/Buttons/play_button_on_hover.png.import
  Assets/UI/Buttons/settings_button_on_hover.png
  Assets/UI/Buttons/settings_button_on_hover.png.import
Labels: enhancement, visual

#197 Added Npc behavior
  Common/ClockBasedEventController.cs
  Common/EventBus.cs
  Features/Dialogue/DialogueSystem.cs
  Features/Dialogue/DialogueUI.cs
  Features/Dialogue/Dialogue_Scene.tscn
  Features/Item/InteractableItem.cs
  Features/NPC/AInteractable.cs
  Features/NPC/Door.cs
  Features/NPC/NPC.tscn
  Features/NPC/NPC1.cs
  Features/NPC/NPC2.cs
  Features/NPC/NPCMother.cs
  Features/NPC/NPC_Moving.tscn
  Features/NPC/Npc.cs
  Features/NPC/NpcInteraction/NpcPlayerInteraction.cs
  Features/NPC/NpcTask/INpcTask.cs
  Features/NPC/NpcTask/ITaskInterruption.cs
  Features/NPC/NpcTask/MovementTask.cs
  Features/NPC/NpcTask/MovementTaskTarget.tscn
  Features/NPC/NpcTask/PlayerInitiatedDialogue.cs
  Features/NPC/NpcTask/TalkToPlayerTask.cs
  Features/NPC/NpcTask/TalkToPlayerTask.tscn
  Features/NPC/NpcType/StandardNpc.cs
  Features/NPC/NpcType/StandardNpc.tscn
  Features/NPC/Routine/NpcRoutine.cs
  Features/NPC/RoutinePlanner/NpcRoutinePlanner.cs
  Features/NPC/SeedBoy.cs
  Features/NPC/VendingMachine/VendingMachineInteractable.cs
  Resources/Dialogue/TutorialDialogue.tres
  Resources/EntityStats_TEST_1.tres
  Resources/EntityStats_TEST_2.tres
  Scenes/GameWorldContainer.tscn
  Scenes/TestScenes/Dialogue/TestDialogue.cs
  Scenes/TestScenes/Dialogue/Test_Dialogue.tscn
  Scenes/TestScenes/NPC/InGameMinutesLabel.cs
  Scenes/TestScenes/NPC/NpcTestingScenes.tscn
  Scenes/TestScenes/TestInventoryScene2.tscn
  Scenes/TestScenes/TestSeedshopScene.tscn
  project.godot
Labels: enhancement

#199 [Feature] Add blurry overlay outside of gameplay
  Features/Cycle/UI/Weather.tscn
  Features/GUI/Book/BookView.cs
  Features/GUI/Book/Wiki/WikiItemList.cs
  Features/GUI/Effects/BlurEffect.cs
  Features/GUI/Effects/BlurEffect.gdshader
  Features/GUI/Effects/BlurEffect.tscn
  Features/GUI/Effects/BlurEffectShaderMaterial.tres
  Features/GUI/Effects/NonGameplayEffect.tscn
  Features/GUI/Effects/TriggerOnNonGameplay.cs
  Features/GUI/Vending/VendingMachineUI.cs
  Features/Shops/GUI/SeedShopView.cs
  Scenes/GUIContainer.tscn
Labels: enhancement, visual

#195 [Bugfix] Selector and Button Indicator throwing errors
  Features/GUI/Book/BookView.tscn
  Features/GUI/Book/Wiki/WikiItemList.tscn
  Features/GUI/Book/Wiki/WikiItemView.cs
  Features/GUI/Book/Wiki/WikiItemView.tscn
  Features/GUI/HUDs/ButtonIndicator.cs
  Features/GUI/HUDs/ButtonIndicator.tscn
  Features/GUI/Hooks/AutoExpandHook.cs
  Features/GUI/Hooks/CopySizeHook.cs
  Features/GUI/Hooks/FollowControlHook.cs
  Features/GUI/Hooks/FollowFocusedHook.cs
  Features/GUI/Selector/UIFocusIcon.cs
Labels: bug

#200 add pier to world
  Assets/Overworld/Garden/pier_ladder.png
  Assets/Overworld/Garden/pier_ladder.png.import
  Scenes/GameWorldContainer.tscn
  Scenes/GardenMapScene.tscn
  Scenes/Pier.tscn
Labels: visual, content

#193 Add Laya placeholder sprite sheets
  Assets/Characters/Laya/Laya_Idle.png
  Assets/Characters/Laya/Laya_Idle.png.import
  Assets/Characters/Laya/Laya_Seed.png
  Assets/Characters/Laya/Laya_Seed.png.import
  Assets/Characters/Laya/Laya_Shears.png
  Assets/Characters/Laya/Laya_Shears.png.import
  Assets/Characters/Laya/Laya_Shovel.png
  Assets/Characters/Laya/Laya_Shovel.png.import
  Assets/Characters/Laya/Laya_Walk_Back.png
  Assets/Characters/Laya/Laya_Walk_Back.png.import
  Assets/Characters/Laya/Laya_Walk_Front.png
  Assets/Characters/Laya/Laya_Walk_Front.png.import
  Assets/Characters/Laya/Laya_Walk_Side.png
  Assets/Characters/Laya/Laya_Walk_Side.png.import
  Assets/Characters/Laya/Laya_Walking.png
  Assets/Characters/Laya/Laya_Walking.png.import
  Assets/Characters/Laya/Laya_Watering.png
  Assets/Characters/Laya/Laya_Watering.png.import
  Features/Player/Player.cs
  Features/Player/Player.tscn
  Features/Player/PlayerSpriteFrames.tres
  Features/Player/StateUseTool.cs
  Features/Player/StateWalk.cs
  Features/Tools/Tool.cs
Labels: visual, content

#198 163 dehydrator UI
  Common/Inputs/GameActions/UINavigation.cs
  Features/Crafting/CraftingSlot.cs
  Features/Crafting/CraftingSlotUi.cs
  Features/Crafting/Dehydrator/CraftingInventory.cs
  Features/Crafting/Dehydrator/Dehydrator.cs
  Features/Crafting/Dehydrator/Dehydrator.tscn
  Features/Crafting/Dehydrator/DehydratorInteractable.cs
  Features/Crafting/Dehydrator/DehydratorInventoryView.tscn
  Features/Crafting/Dehydrator/DehydratorUi.cs
  Features/Crafting/Dehydrator/DehydratorUi.tscn
  Features/Crafting/ICraftingStation.cs
  Features/Crafting/crafting_slot.tscn
  Features/GUI/Items/StorageView.cs
  Features/Item/ItemDatabase.cs
  Features/Player/Player.cs
  Scenes/GUIContainer.tscn
  Scenes/HouseMapScene.tscn
  Scenes/TestScenes/Crafting/TestCrafing.cs
  Scenes/TestScenes/Crafting/Test_Crafing.tscn
Labels: enhancement, content

#272 [Change] Add autoscroll to encyclopedia article for readability.
  Features/GUI/Book/Wiki/WikiArticleView.cs
  Features/GUI/Book/Wiki/WikiArticleView.tscn
  Features/GUI/Components/Scrollable/AutoScrollRichTextLabel.cs
  Features/Shops/RandomStockGenerator.cs
  addons/upg_utils/Plugin.cs
Labels: enhancement

#294 282 Improve visuals and fix MainMenu and settings
  Common/EventBus.cs
  Features/Audio/SfxUI.cs
  Features/GUI/DebugOverlays/DebugOverlay.cs
  Features/GUI/DebugOverlays/DebugOverlays.tscn
  Features/GUI/HUDs/MainMenu/MainMenu.cs
  Features/GUI/HUDs/MainMenu/MainMenu.tscn
  Features/GUI/HUDs/MainMenu/MainMenuButton.cs
  Features/GUI/HUDs/SettingsMenu/DebugButton.cs
  Features/GUI/HUDs/SettingsMenu/ResolutionButton.cs
  Features/GUI/HUDs/SettingsMenu/Settings.tscn
  Features/GUI/HUDs/SettingsMenu/SettingsMenu.cs
Labels: bug, enhancement, visual

#299 [Feature] New interact hint
  Features/GUI/Interactions/InteractHint.cs
  Features/GUI/Interactions/InteractHint.tscn
  Features/Interaction/InteractionManager.cs
  Features/Interaction/InteractionManager.tscn
  Features/Item/InteractableItem.cs
  Features/NPC/NpcInteraction/NpcPlayerInteraction.cs
Labels: enhancement, visual

#297 [Feature] Add item stats to encyclopedia.
  Features/GUI/Book/Wiki/ItemStats.cs
  Features/GUI/Book/Wiki/ItemStats.tscn
  Features/GUI/Book/Wiki/WikiArticleView.cs
  Features/GUI/Book/Wiki/WikiArticleView.tscn
  Features/Item/Components/TagsComponent.cs
Labels: enhancement, visual
